# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: multicode

before:
  hooks:
    - go mod download
builds:
- 
  main: ./cmd/decode/main.go
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  - freebsd
  - openbsd
  - netbsd
  - solaris
  # -plan9
  - dragonfly
  - windows
  goarch:
  - 386
  - amd64
  - arm
  - arm64
  # - ppc64
  # - ppc64le
  # - mips
  # - mipsle
  # - mips64
  # - mips64le
  goarm:
    - 6
    - 7

archive:
  wrap_in_directory: true
  format_overrides:
    - goos: windows
      format: zip
  files:
  - LICENSE
  - README.md


checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next-{{.Commit}}"

nfpm:
  maintainer: Simon Jürgensmeyyer <simon.juergensmeyer@gmail.com>
  homepage: https://github.com/sj14/multicode/
  description: Decode hex, base64 and protobuf recursively with a single command
  license: MIT
  formats:
    - deb
    - rpm

brew:
  # name: dbbench
  # folder: homebrew-tap
  github:
    owner: sj14
    name: homebrew-tap
  description: Decode hex, base64 and protobuf recursively with a single command

release:
  github:
    owner: sj14
    name: multicode
  disable: false
  draft: false
  prerelease: true

changelog:
  filters:
    exclude:
      - typo
